// Do not edit. This file is machine generated by the Resource DLL Wizard.
//---------------------------------------------------------------------------
#define PACKAGE __declspec(package)
#define USERC(FileName) extern PACKAGE _Dummy
#define USERES(FileName) extern PACKAGE _Dummy
#define USEFORMRES(FileName, FormName, AncestorName) extern PACKAGE _Dummy
#pragma hdrstop
int _turboFloat;
//---------------------------------------------------------------------------
/*ITE*/ /*DFMFileType*/ /*AdatbazisKezeles.dfm*/
/*ITE*/ /*DFMFileType*/ /*AdatBeolvasas.dfm*/
/*ITE*/ /*DFMFileType*/ /*BerletEladas.dfm*/
/*ITE*/ /*DFMFileType*/ /*BerletHasznalat.dfm*/
/*ITE*/ /*DFMFileType*/ /*BerletKezeles.dfm*/
/*ITE*/ /*DFMFileType*/ /*BerletPin.dfm*/
/*ITE*/ /*DFMFileType*/ /*Boot.dfm*/
/*ITE*/ /*DFMFileType*/ /*DialogComment.dfm*/
/*ITE*/ /*DFMFileType*/ /*DialogInput.dfm*/
/*ITE*/ /*DFMFileType*/ /*DialogSelectDir.dfm*/
/*ITE*/ /*DFMFileType*/ /*ExtendedViewer.dfm*/
/*ITE*/ /*DFMFileType*/ /*Fizetes.dfm*/
/*ITE*/ /*DFMFileType*/ /*HardwareTeszt.dfm*/
/*ITE*/ /*DFMFileType*/ /*HelpAbout.dfm*/
/*ITE*/ /*DFMFileType*/ /*Kosar.dfm*/
/*ITE*/ /*DFMFileType*/ /*Language.dfm*/
/*ITE*/ /*DFMFileType*/ /*Lista.dfm*/
/*ITE*/ /*DFMFileType*/ /*PasswordChange.dfm*/
/*ITE*/ /*DFMFileType*/ /*PasswordCheck.dfm*/
/*ITE*/ /*DFMFileType*/ /*PenztarKezeles.dfm*/
/*ITE*/ /*DFMFileType*/ /*RendszerAdmin.dfm*/
/*ITE*/ /*DFMFileType*/ /*SystemSettings.dfm*/
/*ITE*/ /*DFMFileType*/ /*SzolariumAdat.dfm*/
/*ITE*/ /*DFMFileType*/ /*SzolariumMain.dfm*/
/*ITE*/ /*DFMFileType*/ /*TermekEladas.dfm*/
/*ITE*/ /*DFMFileType*/ /*TermekKezeles.dfm*/
/*ITE*/ /*DFMFileType*/ /*TermekListaEladas.dfm*/
/*ITE*/ /*DFMFileType*/ /*TermekTipusKezeles.dfm*/
/*ITE*/ /*DFMFileType*/ /*UserKezeles.dfm*/
/*ITE*/ /*RCFileType*/ /*Szolarium_DRC.rc*/
//---------------------------------------------------------------------------
USEFORMRES("AdatbazisKezeles.dfm", FormAdatbazisKezeles, Form); /* TForm: DesignClass */
USEFORMRES("AdatBeolvasas.dfm", FormDataRead, Form); /* TForm: DesignClass */
USEFORMRES("BerletEladas.dfm", FormBerletEladas, Form); /* TForm: DesignClass */
USEFORMRES("BerletHasznalat.dfm", FormBerletHasznalat, Form); /* TForm: DesignClass */
USEFORMRES("BerletKezeles.dfm", FormBerlet, Form); /* TForm: DesignClass */
USEFORMRES("BerletPin.dfm", FormBerletPIN, Form); /* TForm: DesignClass */
USEFORMRES("Boot.dfm", FormBoot, Form); /* TForm: DesignClass */
USEFORMRES("DialogComment.dfm", FormCommentDialog, Form); /* TForm: DesignClass */
USEFORMRES("DialogInput.dfm", FormInputDialog, Form); /* TForm: DesignClass */
USEFORMRES("DialogSelectDir.dfm", FormDialogSelectDir, Form); /* TForm: DesignClass */
USEFORMRES("ExtendedViewer.dfm", FormExtendedViewer, Form); /* TForm: DesignClass */
USEFORMRES("Fizetes.dfm", FormFizetes, Form); /* TForm: DesignClass */
USEFORMRES("HardwareTeszt.dfm", FormHardverTeszt, Form); /* TForm: DesignClass */
USEFORMRES("HelpAbout.dfm", FormHelpAbout, Form); /* TForm: DesignClass */
USEFORMRES("Kosar.dfm", FormKosar, Form); /* TForm: DesignClass */
USEFORMRES("Language.dfm", FormLanguage, Form); /* TForm: DesignClass */
USEFORMRES("Lista.dfm", FormLista, Form); /* TForm: DesignClass */
USEFORMRES("PasswordChange.dfm", FormPasswordChange, Form); /* TForm: DesignClass */
USEFORMRES("PasswordCheck.dfm", FormPasswordCheck, Form); /* TForm: DesignClass */
USEFORMRES("PenztarKezeles.dfm", FormPenztarKezeles, Form); /* TForm: DesignClass */
USEFORMRES("RendszerAdmin.dfm", SystemAdmin, Form); /* TForm: DesignClass */
USEFORMRES("SystemSettings.dfm", FormSystemSettings, Form); /* TForm: DesignClass */
USEFORMRES("SzolariumAdat.dfm", FormSzolariumAdat, Form); /* TForm: DesignClass */
USEFORMRES("SzolariumMain.dfm", FormMain, Form); /* TForm: DesignClass */
USEFORMRES("TermekEladas.dfm", FormTermekEladas, Form); /* TForm: DesignClass */
USEFORMRES("TermekKezeles.dfm", FormTermekKezeles, Form); /* TForm: DesignClass */
USEFORMRES("TermekListaEladas.dfm", FormTermekListaEladas, Form); /* TForm: DesignClass */
USEFORMRES("TermekTipusKezeles.dfm", FormTermekTipus, Form); /* TForm: DesignClass */
USEFORMRES("UserKezeles.dfm", FormUserKezeles, Form); /* TForm: DesignClass */
USERC("Szolarium_DRC.rc");
USERES("Szolarium.res");
//---------------------------------------------------------------------------
#define DllEntryPoint
