//---------------------------------------------------------------------------

#ifndef SetupMainH
#define SetupMainH
//---------------------------------------------------------------------------
#include <Classes.hpp>
#include <Controls.hpp>
#include <StdCtrls.hpp>
#include <Forms.hpp>
#include <ExtCtrls.hpp>
#include <ComCtrls.hpp>
#include <Buttons.hpp>

#include "Classes.h"
#include "Database.h"
//---------------------------------------------------------------------------
typedef struct _typ_berlet_05
{
   char  strVonalkod[20];
   char  strMegjegyzes[50];
   int   nBerletTipus;
   int   nEgyseg;
   int   nErvEv;
   int   nErvHo;
   int   nErvNap;
} typ_berlet_05;
//---------------------------------------------------------------------------
typedef struct _typ_termek_01
{
   DWORD nID;
   char  strVonalkod[20];
   char  strNev[100];
   int   nAr;
   int   nDarab;
} typ_termek_01;
//---------------------------------------------------------------------------
class TFormInstallMain : public TForm
{
__published:	// IDE-managed Components
   TPanel *PanelTablazat;
   TTabControl *TabControlTablazat;
   TGroupBox *GroupBoxTablazatNorm;
   TPanel *Panel2;
   TLabel *Label5;
   TLabel *Label6;
   TLabel *Label7;
   TLabel *Label8;
   TLabel *Label9;
   TLabel *Label10;
   TLabel *Label12;
   TLabel *Label11;
   TLabel *Label13;
   TLabel *Label14;
   TLabel *Label15;
   TLabel *Label16;
   TLabel *Label18;
   TLabel *Label17;
   TLabel *Label19;
   TLabel *Label20;
   TLabel *Label21;
   TLabel *Label22;
   TLabel *Label23;
   TLabel *Label24;
   TEdit *EditPerc0;
   TEdit *EditForint0;
   TEdit *EditPerc1;
   TEdit *EditForint1;
   TEdit *EditPerc2;
   TEdit *EditForint2;
   TEdit *EditPerc3;
   TEdit *EditForint3;
   TEdit *EditPerc4;
   TEdit *EditForint4;
   TEdit *EditPerc5;
   TEdit *EditForint5;
   TEdit *EditPerc6;
   TEdit *EditForint6;
   TEdit *EditPerc7;
   TEdit *EditForint7;
   TEdit *EditPerc8;
   TEdit *EditForint8;
   TEdit *EditPerc9;
   TEdit *EditForint9;
   TPanel *Panel3;
   TLabel *Label44;
   TLabel *Label34;
   TLabel *Label43;
   TLabel *Label33;
   TLabel *Label42;
   TLabel *Label32;
   TLabel *Label41;
   TLabel *Label31;
   TLabel *Label40;
   TLabel *Label30;
   TLabel *Label39;
   TLabel *Label29;
   TLabel *Label38;
   TLabel *Label28;
   TLabel *Label37;
   TLabel *Label27;
   TLabel *Label36;
   TLabel *Label26;
   TLabel *Label35;
   TLabel *Label25;
   TEdit *EditPerc10;
   TEdit *EditForint10;
   TEdit *EditPerc11;
   TEdit *EditForint11;
   TEdit *EditPerc12;
   TEdit *EditForint12;
   TEdit *EditPerc13;
   TEdit *EditForint13;
   TEdit *EditPerc14;
   TEdit *EditForint14;
   TEdit *EditPerc15;
   TEdit *EditForint15;
   TEdit *EditPerc16;
   TEdit *EditForint16;
   TEdit *EditPerc17;
   TEdit *EditForint17;
   TEdit *EditPerc18;
   TEdit *EditForint18;
   TEdit *EditPerc19;
   TEdit *EditForint19;
   TPanel *Panel4;
   TLabel *Label64;
   TLabel *Label54;
   TLabel *Label63;
   TLabel *Label53;
   TLabel *Label62;
   TLabel *Label52;
   TLabel *Label61;
   TLabel *Label51;
   TLabel *Label60;
   TLabel *Label50;
   TLabel *Label59;
   TLabel *Label49;
   TLabel *Label58;
   TLabel *Label48;
   TLabel *Label57;
   TLabel *Label47;
   TLabel *Label56;
   TLabel *Label46;
   TLabel *Label55;
   TLabel *Label45;
   TEdit *EditPerc20;
   TEdit *EditForint20;
   TEdit *EditPerc21;
   TEdit *EditForint21;
   TEdit *EditPerc22;
   TEdit *EditForint22;
   TEdit *EditPerc23;
   TEdit *EditForint23;
   TEdit *EditPerc24;
   TEdit *EditForint24;
   TEdit *EditPerc25;
   TEdit *EditForint25;
   TEdit *EditPerc26;
   TEdit *EditForint26;
   TEdit *EditPerc27;
   TEdit *EditForint27;
   TEdit *EditPerc28;
   TEdit *EditForint28;
   TEdit *EditPerc29;
   TEdit *EditForint29;
   TPanel *Panel5;
   TLabel *Label84;
   TLabel *Label74;
   TLabel *Label83;
   TLabel *Label73;
   TLabel *Label82;
   TLabel *Label72;
   TLabel *Label81;
   TLabel *Label71;
   TLabel *Label80;
   TLabel *Label70;
   TLabel *Label79;
   TLabel *Label69;
   TLabel *Label78;
   TLabel *Label68;
   TLabel *Label77;
   TLabel *Label67;
   TLabel *Label76;
   TLabel *Label66;
   TLabel *Label75;
   TLabel *Label65;
   TEdit *EditPerc30;
   TEdit *EditForint30;
   TEdit *EditPerc31;
   TEdit *EditForint31;
   TEdit *EditPerc32;
   TEdit *EditForint32;
   TEdit *EditPerc33;
   TEdit *EditForint33;
   TEdit *EditPerc34;
   TEdit *EditForint34;
   TEdit *EditPerc35;
   TEdit *EditForint35;
   TEdit *EditPerc36;
   TEdit *EditForint36;
   TEdit *EditPerc37;
   TEdit *EditForint37;
   TEdit *EditPerc38;
   TEdit *EditForint38;
   TEdit *EditPerc39;
   TEdit *EditForint39;
   TGroupBox *GroupBoxTablazatKedv;
   TPanel *Panel6;
   TLabel *Label87;
   TLabel *Label88;
   TLabel *Label89;
   TLabel *Label90;
   TLabel *Label91;
   TLabel *Label92;
   TLabel *Label93;
   TLabel *Label94;
   TLabel *Label95;
   TLabel *Label96;
   TLabel *Label97;
   TLabel *Label98;
   TLabel *Label99;
   TLabel *Label100;
   TLabel *Label101;
   TLabel *Label102;
   TLabel *Label103;
   TLabel *Label104;
   TLabel *Label105;
   TLabel *Label106;
   TEdit *EditKPerc0;
   TEdit *EditKForint0;
   TEdit *EditKPerc1;
   TEdit *EditKForint1;
   TEdit *EditKPerc2;
   TEdit *EditKForint2;
   TEdit *EditKPerc3;
   TEdit *EditKForint3;
   TEdit *EditKPerc4;
   TEdit *EditKForint4;
   TEdit *EditKPerc5;
   TEdit *EditKForint5;
   TEdit *EditKPerc6;
   TEdit *EditKForint6;
   TEdit *EditKPerc7;
   TEdit *EditKForint7;
   TEdit *EditKPerc8;
   TEdit *EditKForint8;
   TEdit *EditKPerc9;
   TEdit *EditKForint9;
   TPanel *Panel7;
   TLabel *Label107;
   TLabel *Label108;
   TLabel *Label109;
   TLabel *Label110;
   TLabel *Label111;
   TLabel *Label112;
   TLabel *Label113;
   TLabel *Label114;
   TLabel *Label115;
   TLabel *Label116;
   TLabel *Label117;
   TLabel *Label118;
   TLabel *Label119;
   TLabel *Label120;
   TLabel *Label121;
   TLabel *Label122;
   TLabel *Label123;
   TLabel *Label124;
   TLabel *Label125;
   TLabel *Label126;
   TEdit *EditKPerc10;
   TEdit *EditKForint10;
   TEdit *EditKPerc11;
   TEdit *EditKForint11;
   TEdit *EditKPerc12;
   TEdit *EditKForint12;
   TEdit *EditKPerc13;
   TEdit *EditKForint13;
   TEdit *EditKPerc14;
   TEdit *EditKForint14;
   TEdit *EditKPerc15;
   TEdit *EditKForint15;
   TEdit *EditKPerc16;
   TEdit *EditKForint16;
   TEdit *EditKPerc17;
   TEdit *EditKForint17;
   TEdit *EditKPerc18;
   TEdit *EditKForint18;
   TEdit *EditKPerc19;
   TEdit *EditKForint19;
   TPanel *Panel8;
   TLabel *Label127;
   TLabel *Label128;
   TLabel *Label129;
   TLabel *Label130;
   TLabel *Label131;
   TLabel *Label132;
   TLabel *Label133;
   TLabel *Label134;
   TLabel *Label135;
   TLabel *Label136;
   TLabel *Label137;
   TLabel *Label138;
   TLabel *Label139;
   TLabel *Label140;
   TLabel *Label141;
   TLabel *Label142;
   TLabel *Label143;
   TLabel *Label144;
   TLabel *Label145;
   TLabel *Label146;
   TEdit *EditKPerc20;
   TEdit *EditKForint20;
   TEdit *EditKPerc21;
   TEdit *EditKForint21;
   TEdit *EditKPerc22;
   TEdit *EditKForint22;
   TEdit *EditKPerc23;
   TEdit *EditKForint23;
   TEdit *EditKPerc24;
   TEdit *EditKForint24;
   TEdit *EditKPerc25;
   TEdit *EditKForint25;
   TEdit *EditKPerc26;
   TEdit *EditKForint26;
   TEdit *EditKPerc27;
   TEdit *EditKForint27;
   TEdit *EditKPerc28;
   TEdit *EditKForint28;
   TEdit *EditKPerc29;
   TEdit *EditKForint29;
   TPanel *Panel9;
   TLabel *Label147;
   TLabel *Label148;
   TLabel *Label149;
   TLabel *Label150;
   TLabel *Label151;
   TLabel *Label152;
   TLabel *Label153;
   TLabel *Label154;
   TLabel *Label155;
   TLabel *Label156;
   TLabel *Label157;
   TLabel *Label158;
   TLabel *Label159;
   TLabel *Label160;
   TLabel *Label161;
   TLabel *Label162;
   TLabel *Label163;
   TLabel *Label164;
   TLabel *Label165;
   TLabel *Label166;
   TEdit *EditKPerc30;
   TEdit *EditKForint30;
   TEdit *EditKPerc31;
   TEdit *EditKForint31;
   TEdit *EditKPerc32;
   TEdit *EditKForint32;
   TEdit *EditKPerc33;
   TEdit *EditKForint33;
   TEdit *EditKPerc34;
   TEdit *EditKForint34;
   TEdit *EditKPerc35;
   TEdit *EditKForint35;
   TEdit *EditKPerc36;
   TEdit *EditKForint36;
   TEdit *EditKPerc37;
   TEdit *EditKForint37;
   TEdit *EditKPerc38;
   TEdit *EditKForint38;
   TEdit *EditKPerc39;
   TEdit *EditKForint39;
   TGroupBox *GroupBoxKedvezmenyesIdo;
   TLabel *Label85;
   TLabel *Label86;
   TLabel *Label167;
   TLabel *Label168;
   TEdit *EditKedvStartO;
   TEdit *EditKedvStartP;
   TEdit *EditKedvStopO;
   TEdit *EditKedvStopP;
   TUpDown *UpDownKedvOraStart;
   TUpDown *UpDownKedvPercStart;
   TUpDown *UpDownKedvOraStop;
   TUpDown *UpDownKedvPercStop;
   TGroupBox *GroupBoxIdoHasznalat;
   TLabel *Label173;
   TEdit *EditIdoHasznalatMax;
   TPanel *PanelSzolarium;
   TGroupBox *GroupBoxInfra;
   TLabel *Label2;
   TEdit *EditIdoSzauna;
   TGroupBox *GroupBoxNevIdo;
   TLabel *Label3;
   TLabel *Label4;
   TEdit *EditIdoVetkozes;
   TEdit *EditIdoUtohutes;
   TGroupBox *GroupBoxCsoUzemora;
   TLabel *Label170;
   TLabel *Label174;
   TEdit *EditCsoUzemoraMax;
   TCheckBox *CheckBoxCsoVisible;
   TPanel *PanelHadver;
   TGroupBox *GroupBox1;
   TLabel *Label1;
   TLabel *Label169;
   TComboBox *ComboBoxPort;
   TComboBox *ComboBoxBaudRate;
   TComboBox *ComboBoxParity;
   TBitBtn *BitBtnTeszt;
   TBitBtn *BitBtnCancel;
   TBitBtn *BitBtnPrev;
   TBitBtn *BitBtnNext;
   TBitBtn *BitBtnExit;
   TLabel *LabelPageCaption;
   TGroupBox *GroupBox2;
   TListBox *ListBoxLog;
   TBitBtn *BitBtnRefresh;
   TPanel *PanelDirectory;
   TGroupBox *GroupBox3;
   TLabel *Label171;
   TEdit *EditDirectory;
   TBitBtn *BitBtnChangeDir;
   TPanel *PanelSetupType;
   TGroupBox *GroupBox4;
   TRadioButton *RB_Setup;
   TRadioButton *RB_Update;
   TPanel *PanelSummary;
   TGroupBox *GroupBox5;
   TListBox *ListBoxSummary;
   TListBox *LanguageStrings;
   TRadioButton *RB_Remove;
   TLabel *Label176;
   TGroupBox *GroupBoxSzolariumSzam;
   TLabel *Label175;
   TEdit *EditSzolariumCount;
   TGroupBox *GroupBox6;
   TLabel *Label172;
   TEdit *EditApplicationCaption;
   TMemo *MemoProgress;
   TBitBtn *BitBtnExitApp;
   void __fastcall TabControlTablazatChange(TObject *Sender);
   void __fastcall FormActivate(TObject *Sender);
   void __fastcall BitBtnTesztClick(TObject *Sender);
   void __fastcall BitBtnCancelClick(TObject *Sender);
   void __fastcall BitBtnPrevClick(TObject *Sender);
   void __fastcall BitBtnNextClick(TObject *Sender);
   void __fastcall BitBtnExitClick(TObject *Sender);
   void __fastcall FormShortCut(TWMKey &Msg, bool &Handled);
   void __fastcall ComboBoxPortChange(TObject *Sender);
   void __fastcall BitBtnRefreshClick(TObject *Sender);
   void __fastcall BitBtnChangeDirClick(TObject *Sender);
   void __fastcall RB_SetupClick(TObject *Sender);
   void __fastcall RB_UpdateClick(TObject *Sender);
   void __fastcall PanelSummaryEnter(TObject *Sender);
   void __fastcall RB_RemoveClick(TObject *Sender);
   void __fastcall BitBtnExitAppClick(TObject *Sender);
private:	// User declarations

   typ_szoliadat  stAdat;
   unsigned int   nPageCount;

   CS_Hardware    *pHardware;
   CS_SerialComm  *pSComm;

   int            nCountSolarium;
   char           strPasswordAdmin[20];
   char           strPasswordUser[20];

   vector<TPanel*>      pPages;
   vector<AnsiString>   pFiles;

   AnsiString           strCurrDir;
   AnsiString           strAppVersion;
   AnsiString           strProgress;

   int                  nLine;

   void SaveDataFromControls();
   void FillControlsWithData();

   void SetIntegerValueInRegistry( AnsiString KeyName, int nValue );
   void SetStringValueInRegistry( AnsiString KeyName, AnsiString strValue );
   int GetIntegerValueFromRegistry( AnsiString KeyName, int nDefValue=0 );
   AnsiString GetStringValueFromRegistry( AnsiString KeyName, AnsiString strDefValue="" );
   AnsiString GetApplicationVersionNumber( LPTSTR lpszFilePath );
   void AddProgressLine( bool isUpdate=false );
   void AddProgressLine( AnsiString strLine, bool isUpdate=false );

public:		// User declarations

   AnsiString LangStr( int LangId );

   __fastcall TFormInstallMain(TComponent* Owner);
};
//---------------------------------------------------------------------------
extern PACKAGE TFormInstallMain *FormInstallMain;
//---------------------------------------------------------------------------
#endif
