// Do not edit. This file is machine generated by the Resource DLL Wizard.
//---------------------------------------------------------------------------
#define PACKAGE __declspec(package)
#define USERC(FileName) extern PACKAGE _Dummy
#define USERES(FileName) extern PACKAGE _Dummy
#define USEFORMRES(FileName, FormName, AncestorName) extern PACKAGE _Dummy
#pragma hdrstop
int _turboFloat;
//---------------------------------------------------------------------------
/*ITE*/ /*DFMFileType*/ /*DialogSelectDir.dfm*/
/*ITE*/ /*DFMFileType*/ /*SetupMain.dfm*/
/*ITE*/ /*RCFileType*/ /*SolariumSetup_DRC.rc*/
//---------------------------------------------------------------------------
USEFORMRES("DialogSelectDir.dfm", FormDialogSelectDir, Form); /* TForm: DesignClass */
USEFORMRES("SetupMain.dfm", FormInstallMain, Form); /* TForm: DesignClass */
USERC("SolariumSetup_DRC.rc");
USERES("SolariumSetup.res");
//---------------------------------------------------------------------------
#define DllEntryPoint
